exp_name: condition_unet_evaluation

seed: 42

base_model_path: pretrained_models/stable-diffusion-v1-5
vae_model_path: pretrained_models/sd-vae-ft-mse
image_encoder_path: pretrained_models/image_encoder
ckpt_dir: '' # set to your checkpoint path

output_dir: 'output/ours'
ckpt_step: 'latest'

datasets: [Objaverse] #, PCN] #[ShapeNet, Objaverse]

ShapeNet:
  dataset_dir: 'data/ShapeNet_processed_1600_no_watertight'
  test_split: 'shapeatlas_utils/shapenet_splits/train_test_split/test_view_split.txt'

Objaverse:
  dataset_dir: 'data/Objaverse_processed_1600_no_watertight'
  test_split: 'shapeatlas_utils/objaverse_splits/teaser_split/teaser_view_split.txt'

PCN:
  dataset_dir: 'data/PCN_processed'
  train_split: 'shapeatlas_utils/PCN_splits/train_test_splits/train_split_cleaned.txt'
  test_split: 'shapeatlas_utils/PCN_splits/train_test_splits/test_view_split_cleaned.txt'

correspondence_file: "shapeatlas_utils/sph2grid_correspondences/correspondences_no_sort.npz"
num_views: 16 # number of views per sample
phase: 'test'
mode: 'train'

batch_size: 1
num_inference_steps: 20
guidance_scale: 1.0 # 3.5
enable_zero_snr: true
weight_dtype: "fp32"

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear" #"linear"
  steps_offset:        1
  clip_sample:         false

enable_xformers_memory_efficient_attention: true
